import Link from "next/link";
import { redirect } from "next/navigation";

import { getViewer } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { SettingsForm } from "@/components/SettingsForm";
import { Badge, Button } from "@/components/ui";
import { planInfo } from "@/lib/constants";
import { isMockProvider } from "@/lib/ai";

export const metadata = { title: "Settings" };
export const dynamic = "force-dynamic";

export default async function SettingsPage() {
  const viewer = await getViewer();
  if (!viewer) redirect("/login");

  const user = await prisma.user.findUnique({
    where: { id: viewer.id },
    select: { birthdate: true, allowMature: true },
  });

  const plan = planInfo(viewer.plan);

  return (
    <div className="mx-auto max-w-2xl px-4 py-8">
      <h1 className="mb-6 text-2xl font-bold tracking-tight">Settings</h1>

      <div className="mb-8 flex items-center justify-between rounded-xl border border-[var(--border)] bg-[var(--surface-raised)] p-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-sm font-medium">{plan.label} plan</span>
            <Badge tone="accent">{viewer.credits} credits left</Badge>
          </div>
          <p className="mt-0.5 text-xs text-faint">
            {plan.credits.toLocaleString()} credits refill every month.
          </p>
        </div>
        <Link href="/pricing">
          <Button variant="outline" size="sm">
            Change plan
          </Button>
        </Link>
      </div>

      {isMockProvider() && (
        <div className="mb-8 rounded-xl border border-amber-500/40 bg-amber-500/10 p-4 text-sm text-amber-100">
          <p className="font-medium text-amber-200">Running on the offline demo model</p>
          <p className="mt-1 text-xs leading-relaxed text-amber-100/80">
            Every feature works, but replies are generated by a local stand-in rather than a real
            model. Set <code className="rounded bg-black/30 px-1">ANTHROPIC_API_KEY</code> in your{" "}
            <code className="rounded bg-black/30 px-1">.env</code> and restart to switch over.
          </p>
        </div>
      )}

      <SettingsForm
        viewer={{
          displayName: viewer.displayName,
          bio: viewer.bio,
          avatarUrl: viewer.avatarUrl,
          plan: viewer.plan,
          allowMature: user?.allowMature ?? false,
          isAdult: viewer.isAdult,
          birthdate: user?.birthdate ? user.birthdate.toISOString().slice(0, 10) : null,
          settings: viewer.settings,
        }}
      />
    </div>
  );
}
