import Link from "next/link";
import { redirect } from "next/navigation";

import { getViewer } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { SettingsForm } from "@/components/SettingsForm";
import { ApiKeysPanel, type KeyStatus } from "@/components/ApiKeysPanel";
import { decryptSecret, maskSecret } from "@/lib/crypto";
import { MODEL_VENDORS } from "@/lib/constants";
import { configuredVendors } from "@/lib/ai";
import { Badge, Button } from "@/components/ui";
import { planInfo } from "@/lib/constants";
import { isMockProvider } from "@/lib/ai";
import { resolveUserKeys } from "@/lib/user-keys";

export const metadata = { title: "Settings" };
export const dynamic = "force-dynamic";

export default async function SettingsPage() {
  const viewer = await getViewer();
  if (!viewer) redirect("/login");

  const user = await prisma.user.findUnique({
    where: { id: viewer.id },
    select: {
      birthdate: true,
      allowMature: true,
      anthropicKeyEnc: true,
      geminiKeyEnc: true,
    },
  });

  // Masked previews only — the stored key is never sent to the browser.
  const fromEnv = configuredVendors();
  const keyStatuses: KeyStatus[] = MODEL_VENDORS.map((vendor) => {
    const stored = vendor === "gemini" ? user?.geminiKeyEnc : user?.anthropicKeyEnc;
    const plain = decryptSecret(stored ?? null);
    return {
      vendor,
      configured: Boolean(plain),
      masked: plain ? maskSecret(plain) : null,
      serverFallback: fromEnv.includes(vendor),
    };
  });

  const plan = planInfo(viewer.plan);
  const userKeys = await resolveUserKeys(viewer.id);
  const onMockModel = isMockProvider(userKeys);

  return (
    <div className="mx-auto max-w-2xl px-4 py-8">
      <h1 className="mb-6 text-2xl font-bold tracking-tight">Settings</h1>

      <div className="mb-8 flex items-center justify-between rounded-xl border border-[var(--border)] bg-[var(--surface-raised)] p-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-sm font-medium">{plan.label} plan</span>
            <Badge tone="accent">{viewer.credits} credits left</Badge>
          </div>
          <p className="mt-0.5 text-xs text-faint">
            {plan.credits.toLocaleString()} credits refill every month.
          </p>
        </div>
        <Link href="/pricing">
          <Button variant="outline" size="sm">
            Change plan
          </Button>
        </Link>
      </div>

      {onMockModel && (
        <div className="mb-8 rounded-xl border border-[var(--tone-warn-border)] bg-[var(--tone-warn-bg)] p-4 text-sm text-[var(--tone-warn-text)]">
          <p className="font-medium text-[var(--tone-warn-strong)]">Running on the offline demo model</p>
          <p className="mt-1 text-xs leading-relaxed text-[var(--tone-warn-text)]">
            Every feature works, but replies are generated by a local stand-in rather than a real
            model. Paste a key under <strong>Your model keys</strong> just below to switch over —
            no file editing and no restart needed.
          </p>
        </div>
      )}

      <ApiKeysPanel initial={keyStatuses} />

      <SettingsForm
        viewer={{
          displayName: viewer.displayName,
          bio: viewer.bio,
          avatarUrl: viewer.avatarUrl,
          plan: viewer.plan,
          allowMature: user?.allowMature ?? false,
          isAdult: viewer.isAdult,
          birthdate: user?.birthdate ? user.birthdate.toISOString().slice(0, 10) : null,
          settings: viewer.settings,
        }}
      />
    </div>
  );
}
